import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextValue {
  language: Language;
  dir: 'rtl' | 'ltr';
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    'nav.home': 'الرئيسية',
    'nav.patriarchs': 'البطاركة',
    'nav.timeline': 'الخط الزمني',
    'nav.about': 'عن المشروع',
    'nav.admin': 'الإدارة',
    'nav.sources': 'المصادر',
    'nav.faith': 'حافظوا على الإيمان',
    'hero.title': 'بطاركة حافظوا على الإيمان',
    'hero.subtitle': 'أرشيف توثيقي لسير بطاركة الكنيسة القبطية الأرثوذكسية ودورهم في الحفاظ على الإيمان.',
    'hero.cta.explore': 'استكشف البطاركة',
    'hero.cta.search': 'ابحث في الأرشيف',
    'home.intro.title': 'عن الأرشيف',
    'home.intro.text': 'هذا الأرشيف التوثيقي يسرد سير بطاركة الكنيسة القبطية الأرثوذكسية عبر القرون، من القديس مرقس الرسول إلى العصر الحديث. يهدف إلى توثيق كيف حافظ كل بطريرك على الإيمان الأرثوذكسي ودافع عنه في وجه التحديات.',
    'home.featured.title': 'بطاركة مختارون',
    'home.explore.title': 'استكشف البطاركة',
    'home.explore.text': 'تصفّح أرشيف البطاركة الكامل واقرأ سير كل بطريرك بالتفصيل.',
    'home.stats.title': 'إحصائيات الأرشيف',
    'home.stats.patriarchs': 'بطاركة موثّقون',
    'home.stats.centuries': 'قرون مغطاة',
    'home.stats.events': 'أحداث تاريخية',
    'home.stats.sources': 'مصادر ومراجع',
    'home.timeline.title': 'معاينة الخط الزمني',
    'home.about.title': 'عن المشروع',
    'home.about.text': 'هذا مشروع تعليمي توثيقي أنشأه طالب كمشروع مسابقة حاسوب. يهدف إلى توثيق تاريخ الكنيسة القبطية الأرثوذكسية وبطاركتها الذين حافظوا على الإيمان عبر القرون. المعلومات مأخوذة من مصادر تاريخية موثوقة ومراجع كنسية معتمدة.',
    'home.sources.title': 'المصادر والمصداقية',
    'home.sources.text': 'نعتمد في توثيقنا على مصادر تاريخية موثوقة منها كتاب تاريخ البطاركة لساويرس ابن المقفع، السنكسار القبطي، مقررات المجامع المسكونية، وكتابات الآباء أنفسهم. كل بطريرك له قائمة مصادر خاصة به.',
    'patriarchs.title': 'أرشيف البطاركة',
    'patriarchs.search_placeholder': 'ابحث باسم البطريرك أو السيرة...',
    'patriarchs.filter_century': 'القرن',
    'patriarchs.filter_all_centuries': 'كل القرون',
    'patriarchs.sort': 'ترتيب',
    'patriarchs.sort.number_asc': 'بالبابوية تصاعدي',
    'patriarchs.sort.number_desc': 'بالبابوية تنازلي',
    'patriarchs.sort.century_asc': 'بالقرن تصاعدي',
    'patriarchs.sort.name_asc': 'بالاسم',
    'patriarchs.read_bio': 'اقرأ السيرة',
    'patriarchs.no_results': 'لا توجد نتائج مطابقة',
    'patriarchs.no_results_text': 'حاول تغيير كلمة البحث أو الفلاتر.',
    'patriarchs.results_count': 'نتيجة',
    'patriarchs.loading': 'جاري التحميل...',
    'patriarchs.error': 'حدث خطأ أثناء تحميل البيانات',
    'patriarchs.error_text': 'تأكد من اتصالك بقاعدة البيانات وحاول مرة أخرى.',
    'details.back': 'العودة إلى البطاركة',
    'details.papal_number': 'البابوية رقم',
    'details.birth': 'الميلاد',
    'details.death': 'النياحة',
    'details.papacy': 'فترة البابوية',
    'details.century': 'القرن',
    'details.biography': 'السيرة الكاملة',
    'details.historical_background': 'الخلفية التاريخية',
    'details.faith_defense': 'كيف حافظ على الإيمان؟',
    'details.challenges': 'التحديات التي واجهها',
    'details.contributions': 'أبرز الإسهامات',
    'details.events': 'الأحداث المهمة',
    'details.sources': 'المصادر والمراجع',
    'details.no_data': 'لا تتوفر معلومات.',
    'details.loading': 'جاري تحميل السيرة...',
    'details.error': 'حدث خطأ أثناء تحميل بيانات البطريرك.',
    'details.not_found': 'لم يتم العثور على هذا البطريرك.',
    'timeline.title': 'الخط الزمني للبطاركة',
    'timeline.subtitle': 'رحلة عبر القرون مع بطاركة الكنيسة القبطية الأرثوذكسية',
    'about.title': 'عن المشروع',
    'about.what': 'ما هو هذا الأرشيف؟',
    'about.what_text': 'بطاركة حافظوا على الإيمان هو أرشيف توثيقي رقمي يهدف إلى توثيق سير بطاركة الكنيسة القبطية الأرثوذكسية ودورهم في الحفاظ على الإيمان المسيحي الأرثوذكسي عبر القرون. يغطي الأرشيف من القديس مرقس الرسول في القرن الأول الميلادي إلى البطاركة المعاصرين.',
    'about.why': 'لماذا تم إنشاؤه؟',
    'about.why_text': 'تم إنشاء هذا المشروع كمشروع تعليمي لمسابقة الحاسوب. الهدف هو توثيق تاريخ الكنيسة القبطية بطريقة منظمة وسهلة الوصول، وإبراز دور البطاركة في الحفاظ على الإيمان في وجه البدع والاضطهادات والتحديات عبر القرون.',
    'about.importance': 'أهمية توثيق تاريخ الكنيسة',
    'about.importance_text': 'تاريخ الكنيسة هو تاريخ الإيمان. من خلال دراسة سير البطاركة، نفهم كيف حفظ الله إيمانه عبر الأجيال، وكيف ثبت الآباء على الحق رغم كل الصعوبات. توثيق هذا التاريخ يحميه من النسيان وينقل حكمته للأجيال القادمة.',
    'about.how': 'كيف تم جمع المعلومات؟',
    'about.how_text': 'المعلومات مأخوذة من مصادر تاريخية موثوقة تشمل: كتاب تاريخ البطاركة لساويرس ابن المقفع، السنكسار القبطي، مقررات المجامع المسكونية، كتابات الآباء أنفسهم، ومراجع تاريخية أكاديمية. يتم الإشارة إلى المصادر لكل بطريرك.',
    'about.disclaimer': 'هذا مشروع تعليمي توثيقي. تم بذل الجهد للتوثيق بدقة من مصادر موثوقة. بعض المعلومات قد تكون غير مكتملة ويمكن إكمالها لاحقاً من قبل الإدارة.',
    'admin.title': 'لوحة الإدارة',
    'admin.login': 'تسجيل الدخول',
    'admin.email': 'البريد الإلكتروني',
    'admin.password': 'كلمة المرور',
    'admin.login_button': 'دخول',
    'admin.login_error': 'خطأ في تسجيل الدخول. تحقق من بياناتك.',
    'admin.logout': 'تسجيل الخروج',
    'admin.add_patriarch': 'إضافة بطريرك',
    'admin.edit': 'تعديل',
    'admin.delete': 'حذف',
    'admin.save': 'حفظ',
    'admin.cancel': 'إلغاء',
    'admin.confirm_delete': 'هل أنت متأكد من الحذف؟',
    'admin.manage_events': 'إدارة الأحداث',
    'admin.manage_sources': 'إدارة المصادر',
    'admin.add_event': 'إضافة حدث',
    'admin.add_source': 'إضافة مصدر',
    'admin.patriarch_list': 'قائمة البطاركة',
    'footer.tagline': 'أرشيف توثيقي لسير بطاركة الكنيسة القبطية الأرثوذكسية',
    'footer.pages': 'الصفحات',
    'footer.about_project': 'مشروع تعليمي لمسابقة الحاسوب',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.retry': 'إعادة المحاولة',
    'common.search': 'بحث',
    'common.close': 'إغلاق',
    'search.advanced': 'بحث متقدم',
    'search.advanced_toggle': 'إظهار البحث المتقدم',
    'search.advanced_hide': 'إخفاء البحث المتقدم',
    'search.papal_number': 'رقم البابوية',
    'search.papacy_period': 'فترة البابوية',
    'search.faith_category': 'فئة الدفاع عن الإيمان',
    'search.all_categories': 'كل الفئات',
    'search.clear_filters': 'مسح الفلاتر',
    'search.no_results': 'لا توجد نتائج مطابقة',
    'search.no_results_text': 'حاول تغيير كلمات البحث أو الفلاتر المستخدمة.',
    'search.results_found': 'نتيجة',
    'search.searching_in': 'البحث في: الأسماء، السير، الدفاع عن الإيمان، الأحداث، الإسهامات، المصادر',
    'category.faith_defense': 'الدفاع عن الإيمان',
    'category.heresy': 'مواجهة البدع والهرطقات',
    'category.teaching': 'الحفاظ على التعليم الكنسي',
    'category.writings': 'التعليم والكتابات',
    'category.persecution': 'مواجهة الاضطهاد',
    'category.service': 'خدمة الكنيسة',
    'category.heritage': 'الحفاظ على التراث',
    'journey.title': 'رحلة عبر التاريخ',
    'journey.subtitle': 'استكشف تاريخ بطاركة الكنيسة القبطية الأرثوذكسية عبر القرون',
    'journey.century': 'القرن',
    'journey.patriarchs_count': 'بطريرك',
    'journey.select_period': 'اختر فترة تاريخية',
    'journey.featured': 'بطاركة بارزون',
    'journey.view_all': 'عرض كل البطاركة في هذه الفترة',
    'sources.title': 'المصادر والمراجع',
    'sources.subtitle': 'توثيق ومصداقية أرشيف البطاركة',
    'sources.why_important': 'لماذا المصادر مهمة؟',
    'sources.why_text': 'يهدف هذا الأرشيف إلى حفظ المعلومات التاريخية بدقة. يجب التحقق من المعلومات مقابل المراجع الموثوقة لضمان النقل الصحيح لتاريخ الكنيسة القبطية الأرثوذكسية وحفظه للأجيال القادمة.',
    'sources.no_sources': 'لا توجد مصادر موثقة مضافة بعد',
    'sources.no_sources_text': 'لم يتم إضافة مصادر موثقة لهذا البطريرك بعد. سيتم إضافتها لاحقاً من قبل الإدارة.',
    'sources.by_type': 'المصادر حسب النوع',
    'sources.all_sources': 'كل المصادر',
    'sources.church_sources': 'مصادر كنسية',
    'sources.historical_refs': 'مراجع تاريخية',
    'sources.books': 'كتب',
    'sources.archives': 'أرشيفات',
    'sources.educational': 'مراجع تعليمية',
    'sources.other': 'مصادر أخرى موثقة',
    'sources.related_patriarch': 'بطريرك مرتبط',
    'sources.total_sources': 'إجمالي المصادر',
    'featured.title': 'بطريرك مميز',
    'featured.subtitle': 'إضاءة على بطريرك من تاريخ الكنيسة القبطية',
    'featured.discover': 'اكتشف سيرته',
    'featured.faith_summary': 'ملخص الدفاع عن الإيمان',
    'faith.title': 'حافظوا على الإيمان',
    'faith.subtitle': 'كيف ساهم بطاركة الكنيسة القبطية الأرثوذكسية في الحفاظ على الإيمان عبر القرون',
    'faith.select_category': 'اختر فئة لاستكشاف البطاركة المرتبطين بها',
    'faith.no_patriarchs': 'لا يوجد بطاركة مرتبطون بهذه الفئة حالياً',
    'faith.no_patriarchs_text': 'لم يتم توثيق معلومات كافية بعد. سيتم إضافة المعلومات لاحقاً.',
    'faith.read_more': 'اقرأ المزيد',
    'faith.contribution': 'الإسهام',
    'timeline.interactive_title': 'الخط الزمني التفاعلي للبطاركة',
    'timeline.explore': 'استكشف الخط الزمني',
    'timeline.click_to_read': 'اضغط لقراءة السيرة الكاملة',
  },
  en: {
    'nav.home': 'Home',
    'nav.patriarchs': 'Patriarchs',
    'nav.timeline': 'Timeline',
    'nav.about': 'About',
    'nav.admin': 'Admin',
    'nav.sources': 'Sources',
    'nav.faith': 'They Preserved the Faith',
    'hero.title': 'Patriarchs Who Preserved the Faith',
    'hero.subtitle': 'A documentary archive of the lives of Coptic Orthodox Patriarchs and their role in preserving the faith.',
    'hero.cta.explore': 'Explore Patriarchs',
    'hero.cta.search': 'Search the Archive',
    'home.intro.title': 'About the Archive',
    'home.intro.text': 'This documentary archive narrates the lives of Coptic Orthodox Patriarchs across centuries, from Saint Mark the Apostle to the modern era. It documents how each patriarch preserved and defended the Orthodox faith.',
    'home.featured.title': 'Featured Patriarchs',
    'home.explore.title': 'Explore the Patriarchs',
    'home.explore.text': 'Browse the full archive of patriarchs and read each biography in detail.',
    'home.stats.title': 'Archive Statistics',
    'home.stats.patriarchs': 'Documented Patriarchs',
    'home.stats.centuries': 'Centuries Covered',
    'home.stats.events': 'Historical Events',
    'home.stats.sources': 'Sources & References',
    'home.timeline.title': 'Timeline Preview',
    'home.about.title': 'About the Project',
    'home.about.text': 'This is an educational documentary project created by a student for a computer competition. It aims to document the history of the Coptic Orthodox Church and its patriarchs who preserved the faith across centuries. Information is sourced from reliable historical and church references.',
    'home.sources.title': 'Sources & Credibility',
    'home.sources.text': 'Our documentation relies on reliable historical sources including the History of the Patriarchs by Severus ibn al-Muqaffa, the Coptic Synaxarium, ecumenical council records, and the writings of the fathers themselves. Each patriarch has its own list of sources.',
    'patriarchs.title': 'Patriarchs Archive',
    'patriarchs.search_placeholder': 'Search by patriarch name or biography...',
    'patriarchs.filter_century': 'Century',
    'patriarchs.filter_all_centuries': 'All Centuries',
    'patriarchs.sort': 'Sort',
    'patriarchs.sort.number_asc': 'Papal Number (Asc)',
    'patriarchs.sort.number_desc': 'Papal Number (Desc)',
    'patriarchs.sort.century_asc': 'Century (Asc)',
    'patriarchs.sort.name_asc': 'Name',
    'patriarchs.read_bio': 'Read Biography',
    'patriarchs.no_results': 'No results found',
    'patriarchs.no_results_text': 'Try changing your search or filters.',
    'patriarchs.results_count': 'results',
    'patriarchs.loading': 'Loading...',
    'patriarchs.error': 'Error loading data',
    'patriarchs.error_text': 'Check your database connection and try again.',
    'details.back': 'Back to Patriarchs',
    'details.papal_number': 'Papal Number',
    'details.birth': 'Birth',
    'details.death': 'Death',
    'details.papacy': 'Papacy Period',
    'details.century': 'Century',
    'details.biography': 'Full Biography',
    'details.historical_background': 'Historical Background',
    'details.faith_defense': 'How Did He Preserve the Faith?',
    'details.challenges': 'Challenges Faced',
    'details.contributions': 'Major Contributions',
    'details.events': 'Important Events',
    'details.sources': 'Sources & References',
    'details.no_data': 'No information available.',
    'details.loading': 'Loading biography...',
    'details.error': 'Error loading patriarch data.',
    'details.not_found': 'Patriarch not found.',
    'timeline.title': 'Patriarchs Timeline',
    'timeline.subtitle': 'A journey through centuries with the Coptic Orthodox Patriarchs',
    'about.title': 'About the Project',
    'about.what': 'What is this archive?',
    'about.what_text': 'Patriarchs Who Preserved the Faith is a digital documentary archive that documents the lives of Coptic Orthodox Patriarchs and their role in preserving the Orthodox Christian faith across centuries. The archive covers from Saint Mark the Apostle in the first century AD to contemporary patriarchs.',
    'about.why': 'Why was it created?',
    'about.why_text': 'This project was created as an educational project for a computer competition. The goal is to document the history of the Coptic Church in an organized and accessible way, highlighting the role of patriarchs in preserving the faith against heresies, persecutions, and challenges across centuries.',
    'about.importance': 'The Importance of Documenting Church History',
    'about.importance_text': 'Church history is the history of faith. By studying the lives of the patriarchs, we understand how God preserved his faith through generations, and how the fathers stood firm for truth despite all difficulties. Documenting this history protects it from oblivion and passes its wisdom to future generations.',
    'about.how': 'How was information collected?',
    'about.how_text': 'Information is drawn from reliable historical sources including: the History of the Patriarchs by Severus ibn al-Muqaffa, the Coptic Synaxarium, ecumenical council records, the writings of the fathers themselves, and academic historical references. Sources are cited for each patriarch.',
    'about.disclaimer': 'This is an educational documentary project. Effort has been made to document accurately from reliable sources. Some information may be incomplete and can be completed later by the administrator.',
    'admin.title': 'Admin Dashboard',
    'admin.login': 'Login',
    'admin.email': 'Email',
    'admin.password': 'Password',
    'admin.login_button': 'Login',
    'admin.login_error': 'Login error. Check your credentials.',
    'admin.logout': 'Logout',
    'admin.add_patriarch': 'Add Patriarch',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.confirm_delete': 'Are you sure you want to delete?',
    'admin.manage_events': 'Manage Events',
    'admin.manage_sources': 'Manage Sources',
    'admin.add_event': 'Add Event',
    'admin.add_source': 'Add Source',
    'admin.patriarch_list': 'Patriarch List',
    'footer.tagline': 'A documentary archive of Coptic Orthodox Patriarchs',
    'footer.pages': 'Pages',
    'footer.about_project': 'Educational project for a computer competition',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.retry': 'Retry',
    'common.search': 'Search',
    'common.close': 'Close',
    'search.advanced': 'Advanced Search',
    'search.advanced_toggle': 'Show advanced search',
    'search.advanced_hide': 'Hide advanced search',
    'search.papal_number': 'Papal Number',
    'search.papacy_period': 'Papacy Period',
    'search.faith_category': 'Faith Defense Category',
    'search.all_categories': 'All Categories',
    'search.clear_filters': 'Clear Filters',
    'search.no_results': 'No matching results',
    'search.no_results_text': 'Try changing your search terms or filters.',
    'search.results_found': 'results',
    'search.searching_in': 'Searching in: names, biographies, faith defense, events, contributions, sources',
    'category.faith_defense': 'Defending the Faith',
    'category.heresy': 'Confronting Heresies',
    'category.teaching': 'Preserving Church Teaching',
    'category.writings': 'Teaching & Writings',
    'category.persecution': 'Facing Persecution',
    'category.service': 'Serving the Church',
    'category.heritage': 'Preserving Heritage',
    'journey.title': 'Journey Through History',
    'journey.subtitle': 'Explore the history of Coptic Orthodox Patriarchs across the centuries',
    'journey.century': 'Century',
    'journey.patriarchs_count': 'patriarchs',
    'journey.select_period': 'Select a historical period',
    'journey.featured': 'Featured Patriarchs',
    'journey.view_all': 'View all patriarchs in this period',
    'sources.title': 'Sources & References',
    'sources.subtitle': 'Documentation and credibility of the patriarchs archive',
    'sources.why_important': 'Why are sources important?',
    'sources.why_text': 'This archive aims to preserve historical information accurately. Information should be verified against reliable references to ensure the correct transmission of Coptic Orthodox Church history to future generations.',
    'sources.no_sources': 'No verified sources added yet',
    'sources.no_sources_text': 'No verified sources have been added for this patriarch yet. They will be added later by the administration.',
    'sources.by_type': 'Sources by Type',
    'sources.all_sources': 'All Sources',
    'sources.church_sources': 'Church Sources',
    'sources.historical_refs': 'Historical References',
    'sources.books': 'Books',
    'sources.archives': 'Archives',
    'sources.educational': 'Educational References',
    'sources.other': 'Other Verified Sources',
    'sources.related_patriarch': 'Related Patriarch',
    'sources.total_sources': 'Total Sources',
    'featured.title': 'Featured Patriarch',
    'featured.subtitle': 'Highlighting a patriarch from Coptic Church history',
    'featured.discover': 'Discover His Story',
    'featured.faith_summary': 'Faith Defense Summary',
    'faith.title': 'They Preserved the Faith',
    'faith.subtitle': 'How Coptic Orthodox Patriarchs contributed to preserving the faith across centuries',
    'faith.select_category': 'Select a category to explore associated patriarchs',
    'faith.no_patriarchs': 'No patriarchs associated with this category yet',
    'faith.no_patriarchs_text': 'Sufficient information has not been documented yet. Information will be added later.',
    'faith.read_more': 'Read more',
    'faith.contribution': 'Contribution',
    'timeline.interactive_title': 'Interactive Patriarchs Timeline',
    'timeline.explore': 'Explore the timeline',
    'timeline.click_to_read': 'Click to read full biography',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem('archive-language');
    return saved === 'en' ? 'en' : 'ar';
  });

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    localStorage.setItem('archive-language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  const toggleLanguage = () => setLang((prev) => (prev === 'ar' ? 'en' : 'ar'));
  const setLanguage = (lang: Language) => setLang(lang);

  const t = (key: string) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, dir, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
